### ISSUE TITLE
Cannot use "select all" to add a second filter for listed file types

### ISSUE THREAD

**Issue by cipricus** [thevladsoft/transparentfolderview#7]
I'm trying to list only audio and video files. I can do one or the other but cannot do both. Only the last added are listed in the widget.

![image](https://github.com/thevladsoft/transparentfolderview/assets/3447868/aec1704d-df20-4c7e-b0d5-0c48f5d23f67)

Thus, it works to select all video file-types (select all, apply). But then, if I do the same for audio, only audio file types are listed. The same happens in the other direction if I add the video file types again: audio files are not listed. — For some reason the previous selected file types are de-selected by the last "select all" option. It happens with any file type or filter (text etc).

The problem seems to be with the "select all" option, and not with the filter as such, because checking file types one by one works: after adding all video file types I was able to add audio file types one by one (acc, mp3 etc), but not by _selecting all_ audio. Testing with the "Hide matching" option, a similar de-selection by last "select all" option happens (I can hide video, but only until I hide audio).

**Comment by thevladsoft** [comment]
It's true that this should be the right behavior. As it is right now, the two buttons "select all" and "deselect all" have a different behavior.
The fix is easy, but I will wait a couple of days to publish it, because I don't want to be seen as if I'm spamming the updates. kdestore have been a little hard with that.
